# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"#\n\x04Info\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2$\n\x04\x44\x65mo\x12\x1c\n\x07GetInfo\x12\x08.Request\x1a\x05.Info\"\x00\x42\nZ\x08service/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010service/'
  _globals['_INFO']._serialized_start=17
  _globals['_INFO']._serialized_end=52
  _globals['_REQUEST']._serialized_start=54
  _globals['_REQUEST']._serialized_end=75
  _globals['_EMPTY']._serialized_start=77
  _globals['_EMPTY']._serialized_end=84
  _globals['_DEMO']._serialized_start=86
  _globals['_DEMO']._serialized_end=122
# @@protoc_insertion_point(module_scope)
