# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomplex.proto\x12\x0f\x65xample.complex\"y\n\x0e\x43omplexMessage\x12\x30\n\tone_dummy\x18\x02 \x01(\x0b\x32\x1d.example.complex.DummyMessage\x12\x35\n\x0emultiple_dummy\x18\x03 \x03(\x0b\x32\x1d.example.complex.DummyMessage\"(\n\x0c\x44ummyMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complex_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMPLEXMESSAGE']._serialized_start=34
  _globals['_COMPLEXMESSAGE']._serialized_end=155
  _globals['_DUMMYMESSAGE']._serialized_start=157
  _globals['_DUMMYMESSAGE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
